# Generated by Django 4.0.2 on 2022-02-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agent', '0003_rename_date_weekend_end_time_and_more'),
        ('service', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='This is deleted datetime', null=True, verbose_name='Deleted Datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('count_adult', models.PositiveIntegerField(default=0)),
                ('count_child', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cost_final', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Agent.agent', verbose_name='Agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer', verbose_name='Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.service', verbose_name='service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
