# Generated by Django 4.0.2 on 2022-02-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_password'),
        ('service', '0003_alter_service_cost_alter_service_time'),
        ('Agent', '0004_alter_agent_options_alter_agent_descriptions_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Agent.agent'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='service.service'),
        ),
    ]
