# Generated by Django 4.0.2 on 2022-02-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price_Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Time_Service'),
        ),
    ]
