# Generated by Django 4.0.2 on 2022-02-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_weekend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekend',
            old_name='Date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='weekend',
            old_name='Time',
            new_name='start_time',
        ),
    ]
