# Generated by Django 4.0.2 on 2022-02-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0003_rename_date_weekend_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='descriptions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
